"""datetime fixed

Revision ID: 4c11ecf38227
Revises: bed8973a9084
Create Date: 2023-04-08 21:31:35.636071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c11ecf38227'
down_revision = 'bed8973a9084'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
