"""datetime fixed

Revision ID: 4f8a8762c729
Revises: 4c11ecf38227
Create Date: 2023-04-08 21:32:44.797402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8a8762c729'
down_revision = '4c11ecf38227'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
