"""datetime fixed

Revision ID: bed8973a9084
Revises: 3803857c7de5
Create Date: 2023-04-08 21:26:59.340902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed8973a9084'
down_revision = '3803857c7de5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
